Repository channel-io/monthly-channel, pull requests merged in 2022-09, with the labels that each got.

#13 feat: 월간채널 9월호 - 웹 추가
  issues/2022-09.md
Labels: docs, docs:web

#15 월간채널 9월 iOS 아티클 추가
  issues/2022-09.md
Labels: docs:ios

#16 월간채널 9월 Backend, DevOps 아티클 추가
  issues/2022-09.md
Labels: docs:backend, docs:devops
