Repository channel-io/monthly-channel, pull requests merged in 2023-02, with the labels that each got.

#45 2023-02호 백엔드, 데브옵스, etc
  issues/2023-02.md
Labels: docs:backend, docs:devops, docs:etc

#46 2023-02호 Channel 파트
  issues/2023-02.md
Labels: docs:channel

#44 2023-02호 웹 파트
  issues/2023-02.md
Labels: docs:web

#43 2023-02월호
  README.md
  issues/2023-02.md
Labels: releases
